-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 14:55:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION;



-- -----------------------------------------------------
-- Table youtube.channel
-- -----------------------------------------------------
DROP TABLE IF EXISTS channel ;

CREATE TABLE IF NOT EXISTS channel (
  channel_ID INT NOT NULL AUTO_INCREMENT,
  channel_name VARCHAR(45) NULL,
  channel_theme VARCHAR(20) NULL,
  channel_date DATE NULL,
  channel_creator_name VARCHAR(45) NULL,
  PRIMARY KEY (channel_ID));


-- -----------------------------------------------------
-- Table youtube.video
-- -----------------------------------------------------
DROP TABLE IF EXISTS video ;

CREATE TABLE IF NOT EXISTS video (
  video_ID INT NOT NULL AUTO_INCREMENT,
  video_channel_ID INT NULL,
  video_like_number INT NULL,
  video_dislike_number INT NULL,
  video_title VARCHAR(45) NULL,
  video_length TIME NULL,
  video_comment_number INT NULL,
  PRIMARY KEY (video_ID));

-- -----------------------------------------------------
-- Table youtube.user
-- -----------------------------------------------------
DROP TABLE IF EXISTS user ;

CREATE TABLE IF NOT EXISTS user (
  user_ID INT NOT NULL AUTO_INCREMENT,
  user_name VARCHAR(45) NULL,
  user_age INT NULL,
  user_gender VARCHAR(6) NULL,
  user_acccount VARCHAR(45) NULL,
  PRIMARY KEY (user_ID));


-- -----------------------------------------------------
-- Table youtube.subscription
-- -----------------------------------------------------
DROP TABLE IF EXISTS subscription ;

CREATE TABLE IF NOT EXISTS subscription (
  subscription_ID INT NOT NULL AUTO_INCREMENT,
  subscription_user_ID INT NULL,
  subscription_channel_ID INT NULL,
  PRIMARY KEY (subscription_ID));
  


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
